In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])
one_hot("amazing restaurant",30)
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
X = padded_reviews
y = sentiment
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())
model.fit(X, y, epochs=50, verbose=0)
loss, accuracy = model.evaluate(X, y)
accuracy
weights = model.get_layer('embedding').get_weights()[0]
len(weights)
weights[13]


[[24, 7], [16, 20], [2, 15], [12, 10, 1], [18, 23, 22], [5, 7], [23, 23, 5], [25, 2], [25, 3], [27, 27]]
[[24  7  0  0]
 [16 20  0  0]
 [ 2 15  0  0]
 [12 10  1  0]
 [18 23 22  0]
 [ 5  7  0  0]
 [23 23  5  0]
 [25  2  0  0]
 [25  3  0  0]
 [27 27  0  0]]
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None
1/1 [==============================] - 0s 231ms/step - loss: 

array([ 0.01643365, -0.04555215,  0.01952689, -0.0142202 ,  0.03760365],
      dtype=float32)